// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum VercelticsBridgePigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum RegistrarDomainAction: Int, CaseIterable {
  case openDomain = 0
  case openRegistrar = 1
  case openCompleteRegistrarApi = 2
}

enum RegistrarDomainStatusTone: Int, CaseIterable {
  case success = 0
  case warning = 1
  case danger = 2
  case progress = 3
  case neutral = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct RegistrarDomainSnapshot: Hashable, CustomStringConvertible {
  var schemaVersion: Int64
  var accountId: String
  var providerId: String
  var providerName: String
  var domainName: String
  var statusLabel: String
  var statusTone: RegistrarDomainStatusTone
  var expiryTone: RegistrarDomainStatusTone
  var expiryValue: String
  var expiryLabel: String
  var expiryDateLabel: String? = nil
  var autoRenewLabel: String
  var transferLockLabel: String
  var privacyLabel: String
  var registeredDateLabel: String? = nil
  var nameservers: [String]
  var canOpenDomain: Bool
  var canOpenRegistrar: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegistrarDomainSnapshot? {
    let schemaVersion = pigeonVar_list[0] as! Int64
    let accountId = pigeonVar_list[1] as! String
    let providerId = pigeonVar_list[2] as! String
    let providerName = pigeonVar_list[3] as! String
    let domainName = pigeonVar_list[4] as! String
    let statusLabel = pigeonVar_list[5] as! String
    let statusTone = pigeonVar_list[6] as! RegistrarDomainStatusTone
    let expiryTone = pigeonVar_list[7] as! RegistrarDomainStatusTone
    let expiryValue = pigeonVar_list[8] as! String
    let expiryLabel = pigeonVar_list[9] as! String
    let expiryDateLabel: String? = nilOrValue(pigeonVar_list[10])
    let autoRenewLabel = pigeonVar_list[11] as! String
    let transferLockLabel = pigeonVar_list[12] as! String
    let privacyLabel = pigeonVar_list[13] as! String
    let registeredDateLabel: String? = nilOrValue(pigeonVar_list[14])
    let nameservers = pigeonVar_list[15] as! [String]
    let canOpenDomain = pigeonVar_list[16] as! Bool
    let canOpenRegistrar = pigeonVar_list[17] as! Bool

    return RegistrarDomainSnapshot(
      schemaVersion: schemaVersion,
      accountId: accountId,
      providerId: providerId,
      providerName: providerName,
      domainName: domainName,
      statusLabel: statusLabel,
      statusTone: statusTone,
      expiryTone: expiryTone,
      expiryValue: expiryValue,
      expiryLabel: expiryLabel,
      expiryDateLabel: expiryDateLabel,
      autoRenewLabel: autoRenewLabel,
      transferLockLabel: transferLockLabel,
      privacyLabel: privacyLabel,
      registeredDateLabel: registeredDateLabel,
      nameservers: nameservers,
      canOpenDomain: canOpenDomain,
      canOpenRegistrar: canOpenRegistrar
    )
  }
  func toList() -> [Any?] {
    return [
      schemaVersion,
      accountId,
      providerId,
      providerName,
      domainName,
      statusLabel,
      statusTone,
      expiryTone,
      expiryValue,
      expiryLabel,
      expiryDateLabel,
      autoRenewLabel,
      transferLockLabel,
      privacyLabel,
      registeredDateLabel,
      nameservers,
      canOpenDomain,
      canOpenRegistrar,
    ]
  }
  static func == (lhs: RegistrarDomainSnapshot, rhs: RegistrarDomainSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VercelticsBridgePigeonInternal.deepEquals(lhs.schemaVersion, rhs.schemaVersion) && VercelticsBridgePigeonInternal.deepEquals(lhs.accountId, rhs.accountId) && VercelticsBridgePigeonInternal.deepEquals(lhs.providerId, rhs.providerId) && VercelticsBridgePigeonInternal.deepEquals(lhs.providerName, rhs.providerName) && VercelticsBridgePigeonInternal.deepEquals(lhs.domainName, rhs.domainName) && VercelticsBridgePigeonInternal.deepEquals(lhs.statusLabel, rhs.statusLabel) && VercelticsBridgePigeonInternal.deepEquals(lhs.statusTone, rhs.statusTone) && VercelticsBridgePigeonInternal.deepEquals(lhs.expiryTone, rhs.expiryTone) && VercelticsBridgePigeonInternal.deepEquals(lhs.expiryValue, rhs.expiryValue) && VercelticsBridgePigeonInternal.deepEquals(lhs.expiryLabel, rhs.expiryLabel) && VercelticsBridgePigeonInternal.deepEquals(lhs.expiryDateLabel, rhs.expiryDateLabel) && VercelticsBridgePigeonInternal.deepEquals(lhs.autoRenewLabel, rhs.autoRenewLabel) && VercelticsBridgePigeonInternal.deepEquals(lhs.transferLockLabel, rhs.transferLockLabel) && VercelticsBridgePigeonInternal.deepEquals(lhs.privacyLabel, rhs.privacyLabel) && VercelticsBridgePigeonInternal.deepEquals(lhs.registeredDateLabel, rhs.registeredDateLabel) && VercelticsBridgePigeonInternal.deepEquals(lhs.nameservers, rhs.nameservers) && VercelticsBridgePigeonInternal.deepEquals(lhs.canOpenDomain, rhs.canOpenDomain) && VercelticsBridgePigeonInternal.deepEquals(lhs.canOpenRegistrar, rhs.canOpenRegistrar)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegistrarDomainSnapshot")
    VercelticsBridgePigeonInternal.deepHash(value: schemaVersion, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: accountId, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: providerId, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: providerName, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: domainName, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: statusLabel, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: statusTone, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: expiryTone, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: expiryValue, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: expiryLabel, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: expiryDateLabel, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: autoRenewLabel, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: transferLockLabel, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: privacyLabel, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: registeredDateLabel, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: nameservers, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: canOpenDomain, hasher: &hasher)
    VercelticsBridgePigeonInternal.deepHash(value: canOpenRegistrar, hasher: &hasher)
  }

  public var description: String {
    return "RegistrarDomainSnapshot(schemaVersion: \(String(describing: schemaVersion)), accountId: \(String(describing: accountId)), providerId: \(String(describing: providerId)), providerName: \(String(describing: providerName)), domainName: \(String(describing: domainName)), statusLabel: \(String(describing: statusLabel)), statusTone: \(String(describing: statusTone)), expiryTone: \(String(describing: expiryTone)), expiryValue: \(String(describing: expiryValue)), expiryLabel: \(String(describing: expiryLabel)), expiryDateLabel: \(String(describing: expiryDateLabel)), autoRenewLabel: \(String(describing: autoRenewLabel)), transferLockLabel: \(String(describing: transferLockLabel)), privacyLabel: \(String(describing: privacyLabel)), registeredDateLabel: \(String(describing: registeredDateLabel)), nameservers: \(String(describing: nameservers)), canOpenDomain: \(String(describing: canOpenDomain)), canOpenRegistrar: \(String(describing: canOpenRegistrar)))"
  }
}

private class VercelticsBridgePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RegistrarDomainAction(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RegistrarDomainStatusTone(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return RegistrarDomainSnapshot.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VercelticsBridgePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RegistrarDomainAction {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RegistrarDomainStatusTone {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? RegistrarDomainSnapshot {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VercelticsBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VercelticsBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VercelticsBridgePigeonCodecWriter(data: data)
  }
}

class VercelticsBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VercelticsBridgePigeonCodec(readerWriter: VercelticsBridgePigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RegistrarDomainHostApi {
  func getRegistrarDomain() throws -> RegistrarDomainSnapshot
  func performRegistrarDomainAction(action: RegistrarDomainAction) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RegistrarDomainHostApiSetup {
  static var codec: FlutterStandardMessageCodec { VercelticsBridgePigeonCodec.shared }
  /// Sets up an instance of `RegistrarDomainHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RegistrarDomainHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getRegistrarDomainChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.verceltics_shared_ui.RegistrarDomainHostApi.getRegistrarDomain\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRegistrarDomainChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getRegistrarDomain()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getRegistrarDomainChannel.setMessageHandler(nil)
    }
    let performRegistrarDomainActionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.verceltics_shared_ui.RegistrarDomainHostApi.performRegistrarDomainAction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      performRegistrarDomainActionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let actionArg = args[0] as! RegistrarDomainAction
        do {
          try api.performRegistrarDomainAction(action: actionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      performRegistrarDomainActionChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol RegistrarDomainFlutterApiProtocol {
  func registrarDomainDidChange(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class RegistrarDomainFlutterApi: RegistrarDomainFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: VercelticsBridgePigeonCodec {
    return VercelticsBridgePigeonCodec.shared
  }
  func registrarDomainDidChange(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.verceltics_shared_ui.RegistrarDomainFlutterApi.registrarDomainDidChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
